import classes from "./css/AboutUs.module.css";

function AboutUs() {
    return (
        <div className={classes.about}>
            <h1>OUR STORY</h1>
            <div className={classes.text}>
                <p>
                    We are a group of four friends from different parts of the world, and we came
                    together with a shared passion for music. Our music is a blend of genres,
                    inspired by our diverse backgrounds and experiences.
                    <br />
                    <br />
                    When we first started playing in local bars and clubs, we didn't know what to
                    expect. But as we began to perform, we could feel the energy in the room. Our
                    music resonated with people, and we were praised for our heartfelt lyrics and
                    soulful melodies.
                    <br />
                    <br />
                    As we continued to play bigger venues and festivals, our fan base grew. We were
                    humbled by the connections we made with people all around the world. They became
                    more than fans, they became family. We are grateful for our journey and the
                    experiences we have had along the way.
                    <br />
                    <br />
                    Generated by <a href="https://chat.openai.com/">Chat GPT</a>.
                </p>
            </div>
        </div>
    );
}

export default AboutUs;
